pipeline {
    agent {
        docker {
            image ''
            label 'linux docker java21'
            reuseNode true
        }
    }

    environment {
        FILE_NAME = 'container'
    }

    stages {
        stage('With Docker') {
            steps {
                sh '''
                    echo "With docker"
                    ls -lha
                    touch $FILE_NAME-yes.txt
                '''
            }
        }
        stage('w/o Docker') {
            agent none

            steps {
                sh '''
                    echo "Without docker"
                    ls -lha
                    touch $FILE_NAME-no.txt
                '''
            }
        }
    }
}