---
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate YAML files
        run: |
          find . -name '*.yml' -o -name '*.yaml' | xargs -I {} yamllint -d "{extends: default, rules: {line-length: {max: 150}}}" {}

  lint-trailing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for trailing whitespace
        run: |
          if grep -rI --include '*.groovy' --include '*.yml' '[[:space:]]$' ./; then
            echo "Trailing whitespace found!"
            exit 1
          else
            echo "No trailing whitespace."
          fi

  lint-groovy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install npm-groovy-lint
        run: npm install -g npm-groovy-lint
      - name: Lint Groovy files
        run: npm-groovy-lint

  # lint-jenkinsfiles:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Cache Jenkins Runner data
  #       uses: actions/cache@v4
  #       with:
  #         path: ~/.jenkinsfile-runner
  #         key: jfr-${{ runner.os }}-2.528.1
  #     - name: Validate Jenkinsfiles in parallel
  #       run: |
  #         find day_* -type f -name 'Jenkinsfile' | xargs -n 1 -P 4 -I {} docker run --rm \
  #           -v ${{ github.workspace }}:/workspace \
  #           -w /workspace \
  #           jenkins/jenkinsfile-runner:latest \
  #           lint -f "{}"