---
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-validate:
    name: Lint & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Run a basic shell script check
        run: |
          echo "Listing top-level folders:"
          ls -la

      - name: Validate YAML files
        run: |
          find . -name '*.yml' -o -name '*.yaml' | xargs -I {} yamllint -d "{extends: default, rules: {line-length: {max: 150}}}" {}

      - name: Check for trailing whitespace (basic linting)
        run: |
          if grep -rI --include '*.groovy' --include '*.yml' '[[:space:]]$' ./; then
            echo "Trailing whitespace found!"
            exit 1
          else
            echo "No trailing whitespace."
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm-groovy-lint
        run: |
          npm install -g npm-groovy-lint

      - name: Validate Jenkinsfile / Groovy pipeline
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            jenkins/jenkinsfile-runner:latest \
            lint -f day_*/**/Jenkinsfile

      - name: Fail if any linting failed
        if: steps.yamllint.outputs.failed == 'true' || steps.trailing.outputs.failed == 'true'
        run: |
          echo "One or more linting checks failed!"
          exit 1
