---
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate YAML files
        run: |
          find . -name '*.yml' -o -name '*.yaml' | xargs -I {} yamllint -c .yamllint {}

  lint-trailing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for trailing whitespace
        run: |
          if grep -rI --include '*.groovy' --include '*.yml' '[[:space:]]$' ./; then
            echo "Trailing whitespace found!"
            exit 1
          else
            echo "No trailing whitespace."
          fi

  lint-groovy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install npm-groovy-lint
        run: npm install -g npm-groovy-lint
      - name: Lint Groovy files
        run: npm-groovy-lint
